name: Publish NPM package

on:
  release:
    types: [published]

jobs:
  publish:
    name: Push NPM package to npmjs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: pnpm 🧰
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Node 🧰
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install 📦
        run: pnpm install

      - name: Publish 🚀 PRERELEASE
        if: 'github.event.release.prerelease'
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish 🚀 PRODUCTION
        if: '!github.event.release.prerelease'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
