name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Push to Docker Hub 🐳
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: marcomontalbano/contentful-migration
          tag_with_ref: true
          tags: latest
