name: Test

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Node 🧰
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install 📦
      run: |
        yarn --frozen-lockfile
        yarn add --dev contentful-migration

    - name: Test 🐛
      run: yarn test:integration
      env:
        CONTENT_MANAGEMENT_TOKEN: ${{ secrets.CONTENT_MANAGEMENT_TOKEN }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
