name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    - name: pnpm 🧰
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Node 🧰
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'

    - name: Install 📦
      run: |
        pnpm install --frozen-lockfile --prod
        pnpm add -D contentful-migration

    - name: Test 🐛
      run: pnpm test:integration
      env:
        CONTENT_MANAGEMENT_TOKEN: ${{ secrets.CONTENT_MANAGEMENT_TOKEN }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
